version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    hostname: elasticsearch
    container_name: elasticsearch
    volumes: 
      - elastic_search:/usr/share/elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    hostname: kibana
    container_name: kibana
    depends_on:
      - elasticsearch
    networks:
      - elastic
    ports:
      - 0.0.0.0:5601:5601
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  grafana:
    image: grafana/grafana
    depends_on:
      - elasticsearch
    hostname: grafana
    container_name: grafana
    networks:
      - elastic
    ports:
      - 0.0.0.0:3000:3000

volumes:
  elastic_search:
    driver: local

networks:
  elastic:
    driver: bridge
