version: '3.8'
services:
    mongo:
      image: mongo
      restart: always
      hostname: mongo
      container_name: mongo
      volumes:
          - mongo_db:/data/db
      networks: mongo-db
      ports:
        - 0.0.0.0:27017:27017
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        hostname: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo-db
        network_mode: host
        ports:
          - 0.0.0.0:8081:8081
volumes:
  mongo_db:
    driver: local

networks:
  mongo_db:
    driver: bridge
